{% set name = "erddaplogs" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erddaplogs-{{ version }}.tar.gz
  sha256: d4da95ddb8053ccbc6d329464a21211553c73890ca82ea45534299f4f51c7640

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - pandas
    - polars >=1.0.0
    - numpy <2
    - pyarrow
    - user-agents

test:
  imports:
    - erddaplogs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/callumrollo/erddaplogs
  summary: Parse log files from an ERDDAP server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - callumrollo
