{% set name = "erddaplogs" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erddaplogs-{{ version }}.tar.gz
  sha256: 61d5288db194e35c5238071dd47640e2b9c790f7f1a543cc21b91b06bbd56877

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - polars >=1.1.0
    - numpy
    - pyarrow
    - user-agents

test:
  imports:
    - erddaplogs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/callumrollo/erddaplogs
  summary: Parse log files from an ERDDAP server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - callumrollo
